# Generated by Django 4.2.5 on 2023-09-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_practice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice_user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='practice_user_registration/'),
        ),
    ]
