# Generated by Django 4.2.5 on 2023-09-26 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_practice_user_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_image', models.ImageField(blank=True, null=True, upload_to='feature_image/')),
                ('product_heading', models.CharField(blank=True, max_length=100, null=True)),
                ('old_price', models.FloatField(blank=True, null=True)),
                ('new_price', models.FloatField(blank=True, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_image/')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product_category')),
            ],
        ),
    ]
