# Generated by Django 4.2.5 on 2023-09-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_product_category_product_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_details',
            old_name='product_heading',
            new_name='product_caption',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='feature_image',
        ),
        migrations.AddField(
            model_name='product_category',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='feature_image/'),
        ),
        migrations.AddField(
            model_name='product_details',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
