# Generated by Django 4.2.5 on 2023-09-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_product_heading_product_details_product_caption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_images', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
    ]
