# Generated by Django 4.2.5 on 2023-09-27 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_images',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='backend.product_details'),
        ),
    ]
