# Generated by Django 4.2.5 on 2023-09-27 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_product_images_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='feature_image',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='category_image',
        ),
        migrations.AddField(
            model_name='product_category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_image/'),
        ),
        migrations.AddField(
            model_name='product_details',
            name='prod_fiture_ima',
            field=models.ImageField(blank=True, null=True, upload_to='fiture_image/'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.product_category'),
        ),
    ]
