# Generated by Django 4.2.5 on 2023-10-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_product_category_feature_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dicounted_carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=250, null=True)),
                ('dicount', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('original_price', models.FloatField(blank=True, null=True)),
                ('dicounted_price', models.FloatField(blank=True, null=True)),
                ('carousel_image', models.ImageField(blank=True, null=True, upload_to='discount_images/')),
            ],
        ),
    ]
