# Generated by Django 4.2.5 on 2023-10-31 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_product_images_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='carousel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_item', to='backend.dicounted_carousel'),
        ),
    ]
