# Generated by Django 4.2.5 on 2023-11-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_product_images_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicounted_carousel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
