# Generated by Django 4.2.5 on 2023-11-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_product_images_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
