# Generated by Django 4.2.5 on 2023-11-01 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_product_images_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_images',
            name='carousel',
        ),
        migrations.AddField(
            model_name='dicounted_carousel',
            name='rel_with_pro_img',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel', to='backend.product_images'),
        ),
        migrations.AlterField(
            model_name='dicounted_carousel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
