# Generated by Django 4.2.5 on 2023-11-03 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_dicounted_carousel_rel_with_pro_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicounted_carousel',
            name='rel_with_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_product', to='backend.product_details'),
        ),
    ]
